CREATE TABLE IF NOT EXISTS `gpiolist` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL ,
	`description`	TEXT NOT NULL,
	`pin`	INTEGER UNIQUE,
	`type`	TEXT NOT NULL,
	`value`	TEXT NOT NULL 
);