CREATE TABLE IF NOT EXISTS `gpiolist` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`description`	TEXT,
	`pin`	INTEGER UNIQUE,
	`type`	TEXT,
	`value`	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `login` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`email`	TEXT UNIQUE,
	`password` TEXT NOT NULL,
	
);